name: Android CI

on:
  push:
    branches:
      - main # or your main development branch like 'develop'
  pull_request:
    branches:
      - main # or your main development branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest # or macos-latest for macOS runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use a recent version

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Use a recent version
        with:
          distribution: 'temurin' # Recommended distribution
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Lint checks
        run: ./gradlew lintDebug

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
